listener:
  slotName: myslot_1
  refreshConnection: 30s
  heartbeatInterval: 10s
logger:
  caller: false
  level: debug
  humanReadable: true
database:
  host: sjb-dev
  port: 5432
  name: app
  user: postgres
#  debug: false
  password: password
#  filter:
#    tables:
#      users:
#        - insert
#        - update
nats:
  address: localhost:4222
  clusterID: test-cluster
  clientID: wal-listener
  topicPrefix: "pre"